version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: geoapi_postgres
    environment:
      POSTGRES_DB: geoapi_db
      POSTGRES_USER: geoapi
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: geoapi_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  api:
    build: .
    container_name: geoapi_api
    environment:
      DATABASE_URL: postgresql://geoapi:password@postgres:5432/geoapi_db
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  celery:
    build: .
    container_name: geoapi_celery
    environment:
      DATABASE_URL: postgresql://geoapi:password@postgres:5432/geoapi_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: celery -A app.celery_app worker --loglevel=info
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: